# Copyright (c) 2025 Joan Fabrégat <j@fabreg.at>
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, subject to the conditions in the full MIT License.
# The Software is provided "as is", without warranty of any kind.

name: document_processor
services:
  document_processor:
    container_name: document_processor
    image: document-processor:latest
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        #- linux/amd64
        - linux/arm64
      args:
        - PORT=80
    ports:
      - "8000:80"
