# Copyright (c) 2025 Joan Fabrégat <j@fabreg.at>
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, subject to the conditions in the full MIT License.
# The Software is provided "as is", without warranty of any kind.

name: document_processor
services:
  document_processor:
    container_name: document_processor
    image: document-processor:latest
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
      #        - linux/arm64
      args:
        VERSION: v0.1.0
        BUILD_ID: docker-desktop
        COMMIT_SHA: docker-desktop
    ports:
      - "8000:80"
    environment:
      ENV: production
      PORT: 80
      THREADS: 4
